on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC every day
  workflow_dispatch: null
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R libraries in renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Download data for shiny app
        run: Rscript data/downloadData.R 
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          
      - name: Deploy to shinyapps.io
        if: github.event_name != 'pull_request'
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript deployShiny.R
